name: test
on: [ push ]

jobs:
  test:
    name: Run CMake Test 🧪
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc cmake

      - name: Build and Run Tests
        run: |
          mkdir build
          cd build
          cmake -DBUILD=test ..
          make
          make test
